/**
 * تحويل رسائل أخطاء قاعدة البيانات (التريغرات والقيود) إلى مفاتيح ترجمة مفهومة للمستخدم.
 * الرسائل في قاعدة البيانات بالإنجليزية عمدًا (ثابتة وقابلة للمطابقة)،
 * والواجهة تعرض الترجمة المناسبة للغة المستخدم.
 */
export type AccountingErrorKey =
  | "not_balanced"
  | "min_two_lines"
  | "zero_total"
  | "header_account"
  | "period_closed"
  | "no_period"
  | "posted_immutable"
  | "already_reversed"
  | "reversal_of_reversal"
  | "permission_denied"
  | "duplicate_code"
  | "type_mismatch"
  | "parent_postable"
  | "account_in_use"
  | "account_currency"
  | "circular"
  | "folio_not_open"
  | "balance_not_zero"
  | "deposit_remaining"
  | "empty_folio"
  | "credit_not_allowed"
  | "credit_limit"
  | "customer_required"
  | "one_credit_customer"
  | "exceeds_balance"
  | "allowance_range"
  | "already_voided"
  | "void_allowances_first"
  | "system_generated"
  | "control_account"
  | "allocation_range"
  | "cash_method_required"
  | "negative_credit"
  | "inactive_reference"
  | "unknown";

const PATTERNS: [RegExp, AccountingErrorKey][] = [
  [/Folio .* is not open|Closed folios/i, "folio_not_open"],
  [/balance must be zero/i, "balance_not_zero"],
  [/Unapplied deposit remains/i, "deposit_remaining"],
  [/Empty folios/i, "empty_folio"],
  [/not allowed credit/i, "credit_not_allowed"],
  [/Credit limit exceeded/i, "credit_limit"],
  [/billing customer is required/i, "customer_required"],
  [/one customer only/i, "one_credit_customer"],
  [/cannot exceed the|exceeds the deposit balance|exceeds the customer/i, "exceeds_balance"],
  [/Allowance must be between/i, "allowance_range"],
  [/already voided|is itself a void/i, "already_voided"],
  [/Void the allowances/i, "void_allowances_first"],
  [/corrected from their source document|generated by their source documents/i, "system_generated"],
  [/Control account/i, "control_account"],
  [/Allocation for invoice|Allocations .* exceed/i, "allocation_range"],
  [/cash or bank payment method/i, "cash_method_required"],
  [/negative customer credit|deposit balance negative/i, "negative_credit"],
  [/not found or inactive/i, "inactive_reference"],
  [/not balanced/i, "not_balanced"],
  [/at least two lines/i, "min_two_lines"],
  [/greater than zero/i, "zero_total"],
  [/header account|inactive or is a header/i, "header_account"],
  [/period .* is closed/i, "period_closed"],
  [/No accounting period/i, "no_period"],
  [/immutable|cannot be (deleted|modified)/i, "posted_immutable"],
  [/already reversed/i, "already_reversed"],
  [/cannot itself be reversed/i, "reversal_of_reversal"],
  [/Permission denied|row-level security/i, "permission_denied"],
  [/chart_of_accounts_hotel_id_code_key|duplicate key/i, "duplicate_code"],
  [/must match parent type|coa_subtype_matches_type/i, "type_mismatch"],
  [/is postable; convert/i, "parent_postable"],
  [/has journal lines|violates foreign key constraint .*journal_entry_lines/i, "account_in_use"],
  [/only accepts entries in its own currency/i, "account_currency"],
  [/Circular/i, "circular"],
];

export function mapDatabaseError(message: string | null | undefined): AccountingErrorKey {
  if (!message) return "unknown";
  for (const [pattern, key] of PATTERNS) if (pattern.test(message)) return key;
  return "unknown";
}
